# Generated by Django 2.0 on 2018-12-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendancee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AtDate', models.DateField(auto_now_add=True)),
                ('Value', models.FloatField(choices=[(1.0, 'Full Day'), (0.5, 'Half_Day'), (0.0, 'Absent')])),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='attendancee',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Employee', unique_for_date=True),
        ),
    ]
