# Generated by Django 2.0 on 2018-12-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancee',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Employee'),
        ),
    ]
