# Generated by Django 2.0 on 2018-12-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20181219_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='AtDate',
            field=models.DateField(),
        ),
    ]
