# Generated by Django 2.0 on 2018-12-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20181219_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='CF_LB',
            field=models.FloatField(default=0, verbose_name='Carry Forward Leave Balance'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Leave_Balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='AtDate',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
