# Generated by Django 2.0 on 2018-12-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20181220_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='CF_LB',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Leave_Balance',
        ),
        migrations.AddField(
            model_name='employee',
            name='CF_LB',
            field=models.FloatField(default=0, verbose_name='Carry Forward Leave Balance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Leave_Balance',
            field=models.FloatField(default=0),
        ),
    ]
