# Generated by Django 2.0 on 2018-12-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20181220_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='AtDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
