# Generated by Django 2.0 on 2018-12-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20181221_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('My_Date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='AtDate',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.Date'),
            preserve_default=False,
        ),
    ]
