# Generated by Django 2.0 on 2018-12-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20181221_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='My_Date',
            field=models.DateField(unique=True),
        ),
    ]
