# Generated by Django 2.0 on 2018-12-27 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_month_leaves_added_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Employee', verbose_name='Employee'),
        ),
    ]
